### ISSUE TITLE
Implement component for displaying a news feed

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/rezultate-vot#105]
A component needs to be implemented to display the news in the news feed.

The component will display the following information:
- date 
- author
- news title
- news text
- news image
- link
- facebook/twitter share buttons
<img width="603" alt="Screenshot 2020-02-27 at 18 46 13" src="https://user-images.githubusercontent.com/15039873/75465573-7f5aab80-5991-11ea-85c0-4ad71b890784.png">

**Comment by claudiuharton** [comment]
I'll take this one
