### ISSUE TITLE
Development setup

### ISSUE THREAD

**Issue by gyula-uszkai** [code4romania/rezultate-vot#107]
Hi

I want to raise some concerns regarding the development effort needed to contribute to the project as follows:
1-aws account is needed at the moment to get the "ElectionsConfig". I think we should find a solution not to force users to create personal AWS accounts (which requires credit card).

2-docker support. Docker is very picky on which windows will it run. As such if you have a different version than expected you can't run docker, hence can't run the app. We should find a workaround for such cases. Maybe use docker toolbox and adjust the setup accordingly.

Hope this will help new developers to have a smoother on-boarding experience.

Br,
Gyula

**Comment by RaduCStefanescu** [comment]
Hi @gyula-uszkai 
Thank you for your input!

1. we are working on a solution to run this project locally using `localstack` as a local substitute for the AWS stack. I believe the solution is already up and running for Windows environments, and you can find more information about this in the README of the project, under `Run the project`

2. we will find a solution for such cases, probably we will provide instructions about running the solution locally, using `dotnet`
