### ISSUE TITLE
[Vote Results] Implement voting presence component

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/rezultate-vot#19]
As part of the web site, we need to display the real time voting presence.
These results will be updated by the backend once every hour.
The component should display information about local presence and also about presence in diaspora.
Checkout the UX for more information:
https://www.figma.com/proto/XoITykcQIv0KLYYTnyqZp4/Rezultate-vot?node-id=36%3A1050&scaling=min-zoom

**Comment by thewindev** [comment]
Implemented by @ascripcaru
