### ISSUE TITLE
Connect to BEC URL and download raw data CSV file

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/rezultate-vot#3]
As part of processing the raw data provided by BEC during election voting count, we need to create a scheduled task, that runs at fixed time interval, set in the configuration file. The following features need to be implemented:

- [x] Implement a scheduled tasks that connects to BEC URL and downloads at fixed time intervals a CSV file
- [x] The CSV file needs to be saved to storage configured in configuration file (Azure/Local storage)
- [x] The CSV file needs versioning - a timestamp needs to be added so that we do not overwrite with latest version

**Comment by thewindev** [comment]
@RaduCStefanescu this issue can be closed as well because it was implemented in this PR: https://github.com/code4romania/rezultate-vot/pull/9

**Comment by RaduCStefanescu** [comment]
Thanks for the heads up @thewindev 
Closing this issue.
