### ISSUE TITLE
[Vote Results] Implement interface with simple mapping logic

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/rezultate-vot#5]
The results in the CSV file need to be consolidated by a simple mapper that aggregates the results for all the parties involved in election. Currently the results in the CSV file are split for all the polling sections, as in the file attached. Each column corresponds to the votes received by a candidate. The following features need to be implemented:

- [x] Aggregate the results in the CSV file for each column containing vote counts for each candidate
- [x] Output a JSON file with results from the aggregation

The format of the JSON file is the following:
```json
[
    {
        "candidate1" : "vote_percentage" 
    },...
]
```

**Comment by thewindev** [comment]
Already resolved.
