### ISSUE TITLE
[Vote Results] Implement frontpage of the web page

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/rezultate-vot#7]
Based on the wireframes, we need the following frontpage developed:
https://www.figma.com/proto/XoITykcQIv0KLYYTnyqZp4/Rezultate-vot?node-id=0%3A1&scaling=min-zoom

The frontpage will contain
- basic description of the website
- the results component
- the statistics retrieved from Monitorizare Vot component
- voting presence component

**Comment by rpuspana** [comment]
Hi,

I will take this in development.

Kind  regards,
Radu

**Comment by rpuspana** [comment]
p.s talked to Bogdan (project creator) and I will working just on the footer for starters. Thank you

**Comment by alexandrutapirdea** [comment]
Hello,

I will work on that.

Thank you,
Alex

**Comment by RaduCStefanescu** [comment]
This issue is already implemented, I will close it
