### ISSUE TITLE
Create Admin page

### ISSUE THREAD

**Issue by thewindev** [code4romania/rezultate-vot#91]
Each election should have a specific configuration that contains the list of candidates, information on how to parse the results for that election, and so on.

**Comment by GabrielMajeri** [comment]
I want to work on this.

I've looked at the [`AdminPanel` component](https://github.com/code4romania/rezultate-vot/blob/master/src/ElectionResults.WebApi/ClientApp/src/components/AdminPanel/AdminPanel.js), and it has options for adding/removing candidates, and for adding/removing files with vote information.

I'm guessing all that's left to do is add a new page displaying the respective component?

**Comment by RaduCStefanescu** [comment]
@GabrielMajeri yes, that would be the idea
We also need to make the admin page available only after a user logs in.
@thewindev is there anything else we want to add?
